def default_params(local_params={}):
    params={}
    
    params['l1'] = "l1"
    params['l2'] = "l2"
    params['inputFile1'] = ""
    params['inputFile2'] = ""
    params['inputFormat'] = "txt"
    params['inputDir'] = '.'
    params['outputDir'] = ''
    params['outputFileName'] = ''
    params['outputFormats'] = ["txt", "tmx", "ces"]
    params['fileId1'] = ''
    params['fileId2'] = ''
    params['addAnchor'] = False
    params['xmlGuide'] = ["s"]
    params['anchorTag'] = ""
    params['col1'] = 0
    params['col2'] = 1
    params['collectionName'] = ""
    params['alignedFileName'] = ""
    params['alreadyAligned'] = False
    params['hashSignInAnchor'] = False
    params['direction'] = '1->2'
    params['inputFileList'] = ''
    params['filePattern'] = r'([^\\/]*)[.](\w\w\w?)[.]\w+$'
    params['writeAnchorPoints'] = False
    params['writeSegmentedInput'] = False
    params['writeIntervals'] = False
    params['printIds'] = False
    params['splitSent1'] = False
    params['splitSent2'] = False
    params['splitSentRegex'] = ""
    params['useSentenceSegmenter'] = False
    params['mergeLines'] = False
    params['adaptativeMode'] = False
    params['verbose'] = False
    params['veryVerbose'] = False
    params['writeAlignableArea'] = False
    params['savePlot'] = False
    params['showPlot'] = False
    params['showSimMat'] = False
    params['detectIntervals'] = False
    params['useNgrams'] = False
    params['doNotRunDTW'] = False
    params['lateGrouping'] = False
    params['noMarginPenalty'] = False
    params['embedModel'] = "sbert"
    params['modelName'] = "sentence-transformers/LaBSE"
    params['cosThreshold'] = 0.4
    params['cosThresholdInOutputAnchors'] = 0.5
    params['ngram'] = 4
    params['diceThreshold'] = 0.05
    params['margin'] = 0.05
    params['kBest'] = 4
    params['deltaX'] = 20
    params['deltaY'] = 3
    params['minHorizontalDensity'] = 0.05
    params['maxDistToTheDiagonal'] = 200
    params['minDensityRatio'] = 0.3
    params['maxGapSize'] = 100
    params['diagBeam'] = 1
    params['localDiagBeam'] = 0.2
    params['sentRatio'] = 0
    params['charRatio'] = 0
    params['reiterateFiltering'] = False
    params['hashSignInAnchor'] = False
    params['dtwBeam'] = 3
    params['localBeamDecay'] = 0.5
    params['distNull'] = 1
    params['noEmptyPair'] = False
    params['no2_2Group'] = False
    params['penalty_n_n'] = 0.06
    params['penalty_0_n'] = 0.15
    params['useShelve'] = False
    params['wordAlignment'] = False
    params['chunkAlignment'] = False
    params['useGPU']=True
    params['printLog'] = False # Print execution log in log file
    params['useEncoder'] = False # Use encoder for concatened sentences in groups 
                              # (if false, single sentence embeddings are summed)
    params['printGap'] = False # Print empty points between intervals
    params['matchFirstPreAnchors'] = True # when True, if the numbers of 
    
    # local params override defaults
    for k,v in local_params.items():
        params[k]=v
    
    return params
